name: Build PDFs
on:
  push:
    branches: [ main ]
    paths:
      - 'reports/templates/**'
      - 'reports/report.css'
      - 'scripts/build-pdfs.js'
      - 'package.json'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci || npm i
      - name: Build PDFs
        run: npm run build-pdfs
      - name: Commit PDFs if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add reports/*.pdf || true
          if git diff --cached --quiet; then
            echo "No PDF changes to commit";
          else
            git commit -m "chore(reports): build PDFs"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin HEAD:${{ github.ref_name }}
          fi
      - name: Upload PDFs as artifact (fallback)
        uses: actions/upload-artifact@v4
        with:
          name: reports-pdfs
          path: reports/*.pdf
          if-no-files-found: ignore
